// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/post/proto/post.proto

package post

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListPostsRequest struct {
	CategoryUid          string   `protobuf:"bytes,1,opt,name=categoryUid,proto3" json:"categoryUid,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	PageNumber           int32    `protobuf:"varint,3,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPostsRequest) Reset()         { *m = ListPostsRequest{} }
func (m *ListPostsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPostsRequest) ProtoMessage()    {}
func (*ListPostsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_414aa58a86974976, []int{0}
}
func (m *ListPostsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPostsRequest.Unmarshal(m, b)
}
func (m *ListPostsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPostsRequest.Marshal(b, m, deterministic)
}
func (dst *ListPostsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPostsRequest.Merge(dst, src)
}
func (m *ListPostsRequest) XXX_Size() int {
	return xxx_messageInfo_ListPostsRequest.Size(m)
}
func (m *ListPostsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPostsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPostsRequest proto.InternalMessageInfo

func (m *ListPostsRequest) GetCategoryUid() string {
	if m != nil {
		return m.CategoryUid
	}
	return ""
}

func (m *ListPostsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListPostsRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

type ListPostsResponse struct {
	Posts                []*SinglePost `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	PageSize             int32         `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	PageNumber           int32         `protobuf:"varint,3,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListPostsResponse) Reset()         { *m = ListPostsResponse{} }
func (m *ListPostsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPostsResponse) ProtoMessage()    {}
func (*ListPostsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_414aa58a86974976, []int{1}
}
func (m *ListPostsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPostsResponse.Unmarshal(m, b)
}
func (m *ListPostsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPostsResponse.Marshal(b, m, deterministic)
}
func (dst *ListPostsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPostsResponse.Merge(dst, src)
}
func (m *ListPostsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPostsResponse.Size(m)
}
func (m *ListPostsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPostsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPostsResponse proto.InternalMessageInfo

func (m *ListPostsResponse) GetPosts() []*SinglePost {
	if m != nil {
		return m.Posts
	}
	return nil
}

func (m *ListPostsResponse) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListPostsResponse) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

type GetPostRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostRequest) Reset()         { *m = GetPostRequest{} }
func (m *GetPostRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostRequest) ProtoMessage()    {}
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_414aa58a86974976, []int{2}
}
func (m *GetPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostRequest.Unmarshal(m, b)
}
func (m *GetPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostRequest.Marshal(b, m, deterministic)
}
func (dst *GetPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostRequest.Merge(dst, src)
}
func (m *GetPostRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostRequest.Size(m)
}
func (m *GetPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostRequest proto.InternalMessageInfo

func (m *GetPostRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type SinglePost struct {
	Uid                  string               `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	UserUid              string               `protobuf:"bytes,2,opt,name=userUid,proto3" json:"userUid,omitempty"`
	CategoryUid          string               `protobuf:"bytes,3,opt,name=categoryUid,proto3" json:"categoryUid,omitempty"`
	Title                string               `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Url                  string               `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	ModifiedAt           *timestamp.Timestamp `protobuf:"bytes,7,opt,name=modifiedAt,proto3" json:"modifiedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SinglePost) Reset()         { *m = SinglePost{} }
func (m *SinglePost) String() string { return proto.CompactTextString(m) }
func (*SinglePost) ProtoMessage()    {}
func (*SinglePost) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_414aa58a86974976, []int{3}
}
func (m *SinglePost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SinglePost.Unmarshal(m, b)
}
func (m *SinglePost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SinglePost.Marshal(b, m, deterministic)
}
func (dst *SinglePost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SinglePost.Merge(dst, src)
}
func (m *SinglePost) XXX_Size() int {
	return xxx_messageInfo_SinglePost.Size(m)
}
func (m *SinglePost) XXX_DiscardUnknown() {
	xxx_messageInfo_SinglePost.DiscardUnknown(m)
}

var xxx_messageInfo_SinglePost proto.InternalMessageInfo

func (m *SinglePost) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *SinglePost) GetUserUid() string {
	if m != nil {
		return m.UserUid
	}
	return ""
}

func (m *SinglePost) GetCategoryUid() string {
	if m != nil {
		return m.CategoryUid
	}
	return ""
}

func (m *SinglePost) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SinglePost) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *SinglePost) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *SinglePost) GetModifiedAt() *timestamp.Timestamp {
	if m != nil {
		return m.ModifiedAt
	}
	return nil
}

type CreatePostRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	UserUid              string   `protobuf:"bytes,3,opt,name=userUid,proto3" json:"userUid,omitempty"`
	CategoryUid          string   `protobuf:"bytes,4,opt,name=categoryUid,proto3" json:"categoryUid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostRequest) Reset()         { *m = CreatePostRequest{} }
func (m *CreatePostRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePostRequest) ProtoMessage()    {}
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_414aa58a86974976, []int{4}
}
func (m *CreatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostRequest.Unmarshal(m, b)
}
func (m *CreatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostRequest.Marshal(b, m, deterministic)
}
func (dst *CreatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostRequest.Merge(dst, src)
}
func (m *CreatePostRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePostRequest.Size(m)
}
func (m *CreatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostRequest proto.InternalMessageInfo

func (m *CreatePostRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreatePostRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CreatePostRequest) GetUserUid() string {
	if m != nil {
		return m.UserUid
	}
	return ""
}

func (m *CreatePostRequest) GetCategoryUid() string {
	if m != nil {
		return m.CategoryUid
	}
	return ""
}

type UpdatePostRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePostRequest) Reset()         { *m = UpdatePostRequest{} }
func (m *UpdatePostRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePostRequest) ProtoMessage()    {}
func (*UpdatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_414aa58a86974976, []int{5}
}
func (m *UpdatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePostRequest.Unmarshal(m, b)
}
func (m *UpdatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePostRequest.Marshal(b, m, deterministic)
}
func (dst *UpdatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePostRequest.Merge(dst, src)
}
func (m *UpdatePostRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePostRequest.Size(m)
}
func (m *UpdatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePostRequest proto.InternalMessageInfo

func (m *UpdatePostRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UpdatePostRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdatePostRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type UpdatePostResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePostResponse) Reset()         { *m = UpdatePostResponse{} }
func (m *UpdatePostResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePostResponse) ProtoMessage()    {}
func (*UpdatePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_414aa58a86974976, []int{6}
}
func (m *UpdatePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePostResponse.Unmarshal(m, b)
}
func (m *UpdatePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePostResponse.Marshal(b, m, deterministic)
}
func (dst *UpdatePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePostResponse.Merge(dst, src)
}
func (m *UpdatePostResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePostResponse.Size(m)
}
func (m *UpdatePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePostResponse proto.InternalMessageInfo

type DeletePostRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePostRequest) Reset()         { *m = DeletePostRequest{} }
func (m *DeletePostRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePostRequest) ProtoMessage()    {}
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_414aa58a86974976, []int{7}
}
func (m *DeletePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePostRequest.Unmarshal(m, b)
}
func (m *DeletePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePostRequest.Marshal(b, m, deterministic)
}
func (dst *DeletePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePostRequest.Merge(dst, src)
}
func (m *DeletePostRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePostRequest.Size(m)
}
func (m *DeletePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePostRequest proto.InternalMessageInfo

func (m *DeletePostRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type DeletePostResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePostResponse) Reset()         { *m = DeletePostResponse{} }
func (m *DeletePostResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePostResponse) ProtoMessage()    {}
func (*DeletePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_414aa58a86974976, []int{8}
}
func (m *DeletePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePostResponse.Unmarshal(m, b)
}
func (m *DeletePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePostResponse.Marshal(b, m, deterministic)
}
func (dst *DeletePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePostResponse.Merge(dst, src)
}
func (m *DeletePostResponse) XXX_Size() int {
	return xxx_messageInfo_DeletePostResponse.Size(m)
}
func (m *DeletePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePostResponse proto.InternalMessageInfo

type CheckPostExistsRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckPostExistsRequest) Reset()         { *m = CheckPostExistsRequest{} }
func (m *CheckPostExistsRequest) String() string { return proto.CompactTextString(m) }
func (*CheckPostExistsRequest) ProtoMessage()    {}
func (*CheckPostExistsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_414aa58a86974976, []int{9}
}
func (m *CheckPostExistsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckPostExistsRequest.Unmarshal(m, b)
}
func (m *CheckPostExistsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckPostExistsRequest.Marshal(b, m, deterministic)
}
func (dst *CheckPostExistsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckPostExistsRequest.Merge(dst, src)
}
func (m *CheckPostExistsRequest) XXX_Size() int {
	return xxx_messageInfo_CheckPostExistsRequest.Size(m)
}
func (m *CheckPostExistsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckPostExistsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckPostExistsRequest proto.InternalMessageInfo

func (m *CheckPostExistsRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type CheckPostExistsResponse struct {
	Exists               bool     `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckPostExistsResponse) Reset()         { *m = CheckPostExistsResponse{} }
func (m *CheckPostExistsResponse) String() string { return proto.CompactTextString(m) }
func (*CheckPostExistsResponse) ProtoMessage()    {}
func (*CheckPostExistsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_414aa58a86974976, []int{10}
}
func (m *CheckPostExistsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckPostExistsResponse.Unmarshal(m, b)
}
func (m *CheckPostExistsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckPostExistsResponse.Marshal(b, m, deterministic)
}
func (dst *CheckPostExistsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckPostExistsResponse.Merge(dst, src)
}
func (m *CheckPostExistsResponse) XXX_Size() int {
	return xxx_messageInfo_CheckPostExistsResponse.Size(m)
}
func (m *CheckPostExistsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckPostExistsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckPostExistsResponse proto.InternalMessageInfo

func (m *CheckPostExistsResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

type GetPostOwnerRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostOwnerRequest) Reset()         { *m = GetPostOwnerRequest{} }
func (m *GetPostOwnerRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostOwnerRequest) ProtoMessage()    {}
func (*GetPostOwnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_414aa58a86974976, []int{11}
}
func (m *GetPostOwnerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostOwnerRequest.Unmarshal(m, b)
}
func (m *GetPostOwnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostOwnerRequest.Marshal(b, m, deterministic)
}
func (dst *GetPostOwnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostOwnerRequest.Merge(dst, src)
}
func (m *GetPostOwnerRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostOwnerRequest.Size(m)
}
func (m *GetPostOwnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostOwnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostOwnerRequest proto.InternalMessageInfo

func (m *GetPostOwnerRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type GetPostOwnerResponse struct {
	OwnerUid             string   `protobuf:"bytes,1,opt,name=ownerUid,proto3" json:"ownerUid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostOwnerResponse) Reset()         { *m = GetPostOwnerResponse{} }
func (m *GetPostOwnerResponse) String() string { return proto.CompactTextString(m) }
func (*GetPostOwnerResponse) ProtoMessage()    {}
func (*GetPostOwnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_414aa58a86974976, []int{12}
}
func (m *GetPostOwnerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostOwnerResponse.Unmarshal(m, b)
}
func (m *GetPostOwnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostOwnerResponse.Marshal(b, m, deterministic)
}
func (dst *GetPostOwnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostOwnerResponse.Merge(dst, src)
}
func (m *GetPostOwnerResponse) XXX_Size() int {
	return xxx_messageInfo_GetPostOwnerResponse.Size(m)
}
func (m *GetPostOwnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostOwnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostOwnerResponse proto.InternalMessageInfo

func (m *GetPostOwnerResponse) GetOwnerUid() string {
	if m != nil {
		return m.OwnerUid
	}
	return ""
}

type ListCategoriesRequest struct {
	PageSize             int32    `protobuf:"varint,1,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	PageNumber           int32    `protobuf:"varint,2,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCategoriesRequest) Reset()         { *m = ListCategoriesRequest{} }
func (m *ListCategoriesRequest) String() string { return proto.CompactTextString(m) }
func (*ListCategoriesRequest) ProtoMessage()    {}
func (*ListCategoriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_414aa58a86974976, []int{13}
}
func (m *ListCategoriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCategoriesRequest.Unmarshal(m, b)
}
func (m *ListCategoriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCategoriesRequest.Marshal(b, m, deterministic)
}
func (dst *ListCategoriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCategoriesRequest.Merge(dst, src)
}
func (m *ListCategoriesRequest) XXX_Size() int {
	return xxx_messageInfo_ListCategoriesRequest.Size(m)
}
func (m *ListCategoriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCategoriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCategoriesRequest proto.InternalMessageInfo

func (m *ListCategoriesRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListCategoriesRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

type ListCategoriesResponse struct {
	Categories           []*SingleCategory `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	PageSize             int32             `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	PageNumber           int32             `protobuf:"varint,3,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListCategoriesResponse) Reset()         { *m = ListCategoriesResponse{} }
func (m *ListCategoriesResponse) String() string { return proto.CompactTextString(m) }
func (*ListCategoriesResponse) ProtoMessage()    {}
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_414aa58a86974976, []int{14}
}
func (m *ListCategoriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCategoriesResponse.Unmarshal(m, b)
}
func (m *ListCategoriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCategoriesResponse.Marshal(b, m, deterministic)
}
func (dst *ListCategoriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCategoriesResponse.Merge(dst, src)
}
func (m *ListCategoriesResponse) XXX_Size() int {
	return xxx_messageInfo_ListCategoriesResponse.Size(m)
}
func (m *ListCategoriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCategoriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCategoriesResponse proto.InternalMessageInfo

func (m *ListCategoriesResponse) GetCategories() []*SingleCategory {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *ListCategoriesResponse) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListCategoriesResponse) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

type SingleCategory struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	UserUid              string   `protobuf:"bytes,2,opt,name=userUid,proto3" json:"userUid,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleCategory) Reset()         { *m = SingleCategory{} }
func (m *SingleCategory) String() string { return proto.CompactTextString(m) }
func (*SingleCategory) ProtoMessage()    {}
func (*SingleCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_414aa58a86974976, []int{15}
}
func (m *SingleCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleCategory.Unmarshal(m, b)
}
func (m *SingleCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleCategory.Marshal(b, m, deterministic)
}
func (dst *SingleCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleCategory.Merge(dst, src)
}
func (m *SingleCategory) XXX_Size() int {
	return xxx_messageInfo_SingleCategory.Size(m)
}
func (m *SingleCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleCategory.DiscardUnknown(m)
}

var xxx_messageInfo_SingleCategory proto.InternalMessageInfo

func (m *SingleCategory) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *SingleCategory) GetUserUid() string {
	if m != nil {
		return m.UserUid
	}
	return ""
}

func (m *SingleCategory) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateCategoryRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	UserUid              string   `protobuf:"bytes,2,opt,name=userUid,proto3" json:"userUid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCategoryRequest) Reset()         { *m = CreateCategoryRequest{} }
func (m *CreateCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCategoryRequest) ProtoMessage()    {}
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_414aa58a86974976, []int{16}
}
func (m *CreateCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCategoryRequest.Unmarshal(m, b)
}
func (m *CreateCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCategoryRequest.Marshal(b, m, deterministic)
}
func (dst *CreateCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCategoryRequest.Merge(dst, src)
}
func (m *CreateCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCategoryRequest.Size(m)
}
func (m *CreateCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCategoryRequest proto.InternalMessageInfo

func (m *CreateCategoryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCategoryRequest) GetUserUid() string {
	if m != nil {
		return m.UserUid
	}
	return ""
}

type GetCategoryAdminByPostRequest struct {
	PostUid              string   `protobuf:"bytes,1,opt,name=postUid,proto3" json:"postUid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCategoryAdminByPostRequest) Reset()         { *m = GetCategoryAdminByPostRequest{} }
func (m *GetCategoryAdminByPostRequest) String() string { return proto.CompactTextString(m) }
func (*GetCategoryAdminByPostRequest) ProtoMessage()    {}
func (*GetCategoryAdminByPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_414aa58a86974976, []int{17}
}
func (m *GetCategoryAdminByPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCategoryAdminByPostRequest.Unmarshal(m, b)
}
func (m *GetCategoryAdminByPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCategoryAdminByPostRequest.Marshal(b, m, deterministic)
}
func (dst *GetCategoryAdminByPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCategoryAdminByPostRequest.Merge(dst, src)
}
func (m *GetCategoryAdminByPostRequest) XXX_Size() int {
	return xxx_messageInfo_GetCategoryAdminByPostRequest.Size(m)
}
func (m *GetCategoryAdminByPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCategoryAdminByPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCategoryAdminByPostRequest proto.InternalMessageInfo

func (m *GetCategoryAdminByPostRequest) GetPostUid() string {
	if m != nil {
		return m.PostUid
	}
	return ""
}

type GetCategoryAdminByPostResponse struct {
	OwnerUid             string   `protobuf:"bytes,1,opt,name=ownerUid,proto3" json:"ownerUid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCategoryAdminByPostResponse) Reset()         { *m = GetCategoryAdminByPostResponse{} }
func (m *GetCategoryAdminByPostResponse) String() string { return proto.CompactTextString(m) }
func (*GetCategoryAdminByPostResponse) ProtoMessage()    {}
func (*GetCategoryAdminByPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_414aa58a86974976, []int{18}
}
func (m *GetCategoryAdminByPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCategoryAdminByPostResponse.Unmarshal(m, b)
}
func (m *GetCategoryAdminByPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCategoryAdminByPostResponse.Marshal(b, m, deterministic)
}
func (dst *GetCategoryAdminByPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCategoryAdminByPostResponse.Merge(dst, src)
}
func (m *GetCategoryAdminByPostResponse) XXX_Size() int {
	return xxx_messageInfo_GetCategoryAdminByPostResponse.Size(m)
}
func (m *GetCategoryAdminByPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCategoryAdminByPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCategoryAdminByPostResponse proto.InternalMessageInfo

func (m *GetCategoryAdminByPostResponse) GetOwnerUid() string {
	if m != nil {
		return m.OwnerUid
	}
	return ""
}

func init() {
	proto.RegisterType((*ListPostsRequest)(nil), "post.ListPostsRequest")
	proto.RegisterType((*ListPostsResponse)(nil), "post.ListPostsResponse")
	proto.RegisterType((*GetPostRequest)(nil), "post.GetPostRequest")
	proto.RegisterType((*SinglePost)(nil), "post.SinglePost")
	proto.RegisterType((*CreatePostRequest)(nil), "post.CreatePostRequest")
	proto.RegisterType((*UpdatePostRequest)(nil), "post.UpdatePostRequest")
	proto.RegisterType((*UpdatePostResponse)(nil), "post.UpdatePostResponse")
	proto.RegisterType((*DeletePostRequest)(nil), "post.DeletePostRequest")
	proto.RegisterType((*DeletePostResponse)(nil), "post.DeletePostResponse")
	proto.RegisterType((*CheckPostExistsRequest)(nil), "post.CheckPostExistsRequest")
	proto.RegisterType((*CheckPostExistsResponse)(nil), "post.CheckPostExistsResponse")
	proto.RegisterType((*GetPostOwnerRequest)(nil), "post.GetPostOwnerRequest")
	proto.RegisterType((*GetPostOwnerResponse)(nil), "post.GetPostOwnerResponse")
	proto.RegisterType((*ListCategoriesRequest)(nil), "post.ListCategoriesRequest")
	proto.RegisterType((*ListCategoriesResponse)(nil), "post.ListCategoriesResponse")
	proto.RegisterType((*SingleCategory)(nil), "post.SingleCategory")
	proto.RegisterType((*CreateCategoryRequest)(nil), "post.CreateCategoryRequest")
	proto.RegisterType((*GetCategoryAdminByPostRequest)(nil), "post.GetCategoryAdminByPostRequest")
	proto.RegisterType((*GetCategoryAdminByPostResponse)(nil), "post.GetCategoryAdminByPostResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostClient is the client API for Post service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostClient interface {
	ListPosts(ctx context.Context, in *ListPostsRequest, opts ...grpc.CallOption) (*ListPostsResponse, error)
	GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*SinglePost, error)
	CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*SinglePost, error)
	UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*UpdatePostResponse, error)
	DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*DeletePostResponse, error)
	CheckPostExists(ctx context.Context, in *CheckPostExistsRequest, opts ...grpc.CallOption) (*CheckPostExistsResponse, error)
	GetPostOwner(ctx context.Context, in *GetPostOwnerRequest, opts ...grpc.CallOption) (*GetPostOwnerResponse, error)
	ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*ListCategoriesResponse, error)
	GetCategoryAdminByPost(ctx context.Context, in *GetCategoryAdminByPostRequest, opts ...grpc.CallOption) (*GetCategoryAdminByPostResponse, error)
	CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*SingleCategory, error)
}

type postClient struct {
	cc *grpc.ClientConn
}

func NewPostClient(cc *grpc.ClientConn) PostClient {
	return &postClient{cc}
}

func (c *postClient) ListPosts(ctx context.Context, in *ListPostsRequest, opts ...grpc.CallOption) (*ListPostsResponse, error) {
	out := new(ListPostsResponse)
	err := c.cc.Invoke(ctx, "/post.Post/ListPosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*SinglePost, error) {
	out := new(SinglePost)
	err := c.cc.Invoke(ctx, "/post.Post/GetPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*SinglePost, error) {
	out := new(SinglePost)
	err := c.cc.Invoke(ctx, "/post.Post/CreatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*UpdatePostResponse, error) {
	out := new(UpdatePostResponse)
	err := c.cc.Invoke(ctx, "/post.Post/UpdatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*DeletePostResponse, error) {
	out := new(DeletePostResponse)
	err := c.cc.Invoke(ctx, "/post.Post/DeletePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) CheckPostExists(ctx context.Context, in *CheckPostExistsRequest, opts ...grpc.CallOption) (*CheckPostExistsResponse, error) {
	out := new(CheckPostExistsResponse)
	err := c.cc.Invoke(ctx, "/post.Post/CheckPostExists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) GetPostOwner(ctx context.Context, in *GetPostOwnerRequest, opts ...grpc.CallOption) (*GetPostOwnerResponse, error) {
	out := new(GetPostOwnerResponse)
	err := c.cc.Invoke(ctx, "/post.Post/GetPostOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*ListCategoriesResponse, error) {
	out := new(ListCategoriesResponse)
	err := c.cc.Invoke(ctx, "/post.Post/ListCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) GetCategoryAdminByPost(ctx context.Context, in *GetCategoryAdminByPostRequest, opts ...grpc.CallOption) (*GetCategoryAdminByPostResponse, error) {
	out := new(GetCategoryAdminByPostResponse)
	err := c.cc.Invoke(ctx, "/post.Post/GetCategoryAdminByPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*SingleCategory, error) {
	out := new(SingleCategory)
	err := c.cc.Invoke(ctx, "/post.Post/CreateCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostServer is the server API for Post service.
type PostServer interface {
	ListPosts(context.Context, *ListPostsRequest) (*ListPostsResponse, error)
	GetPost(context.Context, *GetPostRequest) (*SinglePost, error)
	CreatePost(context.Context, *CreatePostRequest) (*SinglePost, error)
	UpdatePost(context.Context, *UpdatePostRequest) (*UpdatePostResponse, error)
	DeletePost(context.Context, *DeletePostRequest) (*DeletePostResponse, error)
	CheckPostExists(context.Context, *CheckPostExistsRequest) (*CheckPostExistsResponse, error)
	GetPostOwner(context.Context, *GetPostOwnerRequest) (*GetPostOwnerResponse, error)
	ListCategories(context.Context, *ListCategoriesRequest) (*ListCategoriesResponse, error)
	GetCategoryAdminByPost(context.Context, *GetCategoryAdminByPostRequest) (*GetCategoryAdminByPostResponse, error)
	CreateCategory(context.Context, *CreateCategoryRequest) (*SingleCategory, error)
}

func RegisterPostServer(s *grpc.Server, srv PostServer) {
	s.RegisterService(&_Post_serviceDesc, srv)
}

func _Post_ListPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).ListPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.Post/ListPosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).ListPosts(ctx, req.(*ListPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Post_GetPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).GetPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.Post/GetPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).GetPost(ctx, req.(*GetPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Post_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.Post/CreatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).CreatePost(ctx, req.(*CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Post_UpdatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).UpdatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.Post/UpdatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).UpdatePost(ctx, req.(*UpdatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Post_DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.Post/DeletePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).DeletePost(ctx, req.(*DeletePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Post_CheckPostExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPostExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).CheckPostExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.Post/CheckPostExists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).CheckPostExists(ctx, req.(*CheckPostExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Post_GetPostOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).GetPostOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.Post/GetPostOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).GetPostOwner(ctx, req.(*GetPostOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Post_ListCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).ListCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.Post/ListCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).ListCategories(ctx, req.(*ListCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Post_GetCategoryAdminByPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryAdminByPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).GetCategoryAdminByPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.Post/GetCategoryAdminByPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).GetCategoryAdminByPost(ctx, req.(*GetCategoryAdminByPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Post_CreateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).CreateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.Post/CreateCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).CreateCategory(ctx, req.(*CreateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Post_serviceDesc = grpc.ServiceDesc{
	ServiceName: "post.Post",
	HandlerType: (*PostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPosts",
			Handler:    _Post_ListPosts_Handler,
		},
		{
			MethodName: "GetPost",
			Handler:    _Post_GetPost_Handler,
		},
		{
			MethodName: "CreatePost",
			Handler:    _Post_CreatePost_Handler,
		},
		{
			MethodName: "UpdatePost",
			Handler:    _Post_UpdatePost_Handler,
		},
		{
			MethodName: "DeletePost",
			Handler:    _Post_DeletePost_Handler,
		},
		{
			MethodName: "CheckPostExists",
			Handler:    _Post_CheckPostExists_Handler,
		},
		{
			MethodName: "GetPostOwner",
			Handler:    _Post_GetPostOwner_Handler,
		},
		{
			MethodName: "ListCategories",
			Handler:    _Post_ListCategories_Handler,
		},
		{
			MethodName: "GetCategoryAdminByPost",
			Handler:    _Post_GetCategoryAdminByPost_Handler,
		},
		{
			MethodName: "CreateCategory",
			Handler:    _Post_CreateCategory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/post/proto/post.proto",
}

func init() { proto.RegisterFile("pkg/post/proto/post.proto", fileDescriptor_post_414aa58a86974976) }

var fileDescriptor_post_414aa58a86974976 = []byte{
	// 717 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xdd, 0x4e, 0xdb, 0x4c,
	0x10, 0x95, 0xf3, 0x43, 0xe0, 0xf0, 0x29, 0x1f, 0x6c, 0x43, 0x30, 0x5b, 0xa0, 0x91, 0xfb, 0x17,
	0xf5, 0x22, 0x88, 0xb4, 0x52, 0x7f, 0x84, 0x84, 0x68, 0x8a, 0xb8, 0x68, 0x4b, 0x91, 0x29, 0x0f,
	0x10, 0x92, 0x25, 0xb5, 0x48, 0x62, 0xd7, 0xde, 0x88, 0xa6, 0x8f, 0xd0, 0xa7, 0xea, 0x63, 0xf5,
	0xb2, 0xda, 0xf5, 0xda, 0xde, 0x64, 0x1d, 0x50, 0xc5, 0xdd, 0xee, 0xce, 0xcc, 0x99, 0xe3, 0x99,
	0x39, 0x63, 0x6c, 0x05, 0xd7, 0x83, 0xbd, 0xc0, 0x8f, 0xf8, 0x5e, 0x10, 0xfa, 0xdc, 0x97, 0xc7,
	0x96, 0x3c, 0x92, 0x92, 0x38, 0xd3, 0x47, 0x03, 0xdf, 0x1f, 0x0c, 0x59, 0x6c, 0xbe, 0x9c, 0x5c,
	0xed, 0x71, 0x6f, 0xc4, 0x22, 0xde, 0x1d, 0x05, 0xb1, 0x9b, 0x13, 0x60, 0xed, 0x93, 0x17, 0xf1,
	0x33, 0x3f, 0xe2, 0x91, 0xcb, 0xbe, 0x4f, 0x58, 0xc4, 0x49, 0x03, 0xab, 0xbd, 0x2e, 0x67, 0x03,
	0x3f, 0x9c, 0x5e, 0x78, 0x7d, 0xdb, 0x6a, 0x58, 0xcd, 0x15, 0x57, 0x7f, 0x22, 0x14, 0xcb, 0x41,
	0x77, 0xc0, 0xce, 0xbd, 0x9f, 0xcc, 0x2e, 0x34, 0xac, 0x66, 0xd9, 0x4d, 0xef, 0x64, 0x17, 0x10,
	0xe7, 0xd3, 0xc9, 0xe8, 0x92, 0x85, 0x76, 0x51, 0x5a, 0xb5, 0x17, 0xe7, 0x06, 0xeb, 0x5a, 0xc6,
	0x28, 0xf0, 0xc7, 0x11, 0x23, 0xcf, 0x50, 0x16, 0x7c, 0x23, 0xdb, 0x6a, 0x14, 0x9b, 0xab, 0xed,
	0xb5, 0x96, 0xfc, 0x92, 0x73, 0x6f, 0x3c, 0x18, 0x32, 0xe1, 0xe9, 0xc6, 0xe6, 0x7b, 0x25, 0x76,
	0x50, 0x3d, 0x61, 0x32, 0x6f, 0xf2, 0xa1, 0x6b, 0x28, 0x4e, 0xd2, 0x0f, 0x14, 0x47, 0xe7, 0x8f,
	0x05, 0x64, 0x59, 0x4d, 0x07, 0x62, 0xa3, 0x32, 0x89, 0x58, 0x28, 0xea, 0x52, 0x90, 0xaf, 0xc9,
	0x75, 0xbe, 0x6a, 0x45, 0xb3, 0x6a, 0x35, 0x94, 0xb9, 0xc7, 0x87, 0xcc, 0x2e, 0x49, 0x5b, 0x7c,
	0x91, 0x39, 0xc2, 0xa1, 0x5d, 0x56, 0x39, 0xc2, 0x21, 0x79, 0x83, 0x95, 0x5e, 0xc8, 0xba, 0x9c,
	0xf5, 0x8f, 0xb8, 0xbd, 0xd4, 0xb0, 0x9a, 0xab, 0x6d, 0xda, 0x8a, 0x1b, 0xd9, 0x4a, 0x1a, 0xd9,
	0xfa, 0x9a, 0x34, 0xd2, 0xcd, 0x9c, 0xc9, 0x3b, 0x60, 0xe4, 0xf7, 0xbd, 0x2b, 0x4f, 0x86, 0x56,
	0xee, 0x0c, 0xd5, 0xbc, 0x45, 0x5f, 0x3a, 0x12, 0x48, 0xaf, 0x50, 0x4a, 0xd9, 0xca, 0xa1, 0x5c,
	0xc8, 0x28, 0x6b, 0x65, 0x29, 0xde, 0x5a, 0x96, 0x92, 0x51, 0x16, 0xe7, 0x33, 0xd6, 0x2f, 0x82,
	0xfe, 0x5c, 0x62, 0xb3, 0xf2, 0x29, 0x95, 0x42, 0x0e, 0x95, 0x62, 0x4a, 0xc5, 0xa9, 0x81, 0xe8,
	0x70, 0xf1, 0x80, 0x39, 0x4f, 0xb1, 0xfe, 0x81, 0x0d, 0xd9, 0x1d, 0x49, 0x44, 0xb0, 0xee, 0xa6,
	0x82, 0x5f, 0xa0, 0xde, 0xf9, 0xc6, 0x7a, 0xd7, 0xe2, 0xf1, 0xf8, 0x87, 0xa7, 0x49, 0xc5, 0x44,
	0xd8, 0xc7, 0xa6, 0xe1, 0xab, 0x86, 0xbc, 0x8e, 0x25, 0x26, 0x5f, 0xa4, 0xff, 0xb2, 0xab, 0x6e,
	0xce, 0x73, 0x3c, 0x50, 0x83, 0xf9, 0xe5, 0x66, 0xcc, 0xc2, 0xc5, 0xd8, 0x6d, 0xd4, 0x66, 0x1d,
	0x15, 0x30, 0xc5, 0xb2, 0x2f, 0x1e, 0x32, 0xb5, 0xa6, 0x77, 0xe7, 0x1c, 0x1b, 0x42, 0x6e, 0x9d,
	0xb8, 0xe0, 0x1e, 0x4b, 0xa9, 0xeb, 0x52, 0xb2, 0x6e, 0x95, 0x52, 0xc1, 0x90, 0xd2, 0x2f, 0x0b,
	0xf5, 0x79, 0x54, 0xc5, 0xe5, 0x15, 0xd0, 0x4b, 0x5f, 0x95, 0x9c, 0x6b, 0xba, 0x9c, 0x55, 0xcc,
	0xd4, 0xd5, 0xfc, 0xee, 0xa5, 0xeb, 0x33, 0x54, 0x67, 0x91, 0xff, 0x49, 0xb6, 0x04, 0xa5, 0x71,
	0x77, 0xc4, 0xd4, 0x04, 0xc9, 0xb3, 0x73, 0x8c, 0x8d, 0x58, 0x0a, 0x29, 0x57, 0x55, 0xb3, 0xc4,
	0xd9, 0xca, 0x9c, 0x17, 0x43, 0x3b, 0x6f, 0xb1, 0x73, 0xc2, 0x92, 0x1a, 0x4d, 0x8f, 0xfa, 0x23,
	0x6f, 0xfc, 0x7e, 0xaa, 0xcf, 0x9f, 0x8d, 0x8a, 0x28, 0x4c, 0xd6, 0xb6, 0xe4, 0xea, 0x1c, 0x60,
	0x77, 0x51, 0xe8, 0xdd, 0x3d, 0x6f, 0xff, 0x2e, 0xa3, 0x24, 0xf7, 0xd7, 0x01, 0x56, 0xd2, 0x5d,
	0x4b, 0xea, 0x71, 0x17, 0xe6, 0xd7, 0x3d, 0xdd, 0x34, 0xde, 0x55, 0x8a, 0x7d, 0x54, 0xd4, 0xb8,
	0x11, 0xd5, 0xc1, 0xd9, 0xfd, 0x49, 0x8d, 0x35, 0x4d, 0x5e, 0x03, 0xd9, 0x12, 0x21, 0x0a, 0xd9,
	0x58, 0x2b, 0x39, 0x81, 0x87, 0x40, 0xa6, 0xda, 0x24, 0xd0, 0x58, 0x0b, 0xd4, 0x36, 0x0d, 0x8a,
	0xec, 0x21, 0x90, 0x29, 0x37, 0x01, 0x30, 0x24, 0x9f, 0x00, 0x98, 0x22, 0x27, 0xa7, 0xf8, 0x7f,
	0x4e, 0xb8, 0x64, 0x5b, 0xf1, 0xcf, 0xd5, 0x3e, 0xdd, 0x59, 0x60, 0x55, 0x78, 0xc7, 0xf8, 0x4f,
	0x17, 0x2b, 0xd9, 0x9a, 0x29, 0xa1, 0xae, 0x74, 0x4a, 0xf3, 0x4c, 0x0a, 0xe6, 0x23, 0xaa, 0xb3,
	0x4a, 0x23, 0x0f, 0xb3, 0x7e, 0x19, 0xaa, 0xa6, 0xdb, 0xf9, 0x46, 0x05, 0xd6, 0x43, 0x3d, 0x7f,
	0xac, 0xc8, 0xe3, 0x94, 0xc2, 0xe2, 0x79, 0xa5, 0x4f, 0x6e, 0x77, 0x52, 0x49, 0x3a, 0xa8, 0xce,
	0xaa, 0x27, 0x61, 0x9c, 0xab, 0x29, 0x9a, 0xbb, 0x1c, 0x2e, 0x97, 0xe4, 0xdf, 0xea, 0xe5, 0xdf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x68, 0x4f, 0x67, 0x20, 0xe2, 0x08, 0x00, 0x00,
}
